/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_identicalsoftware_javalibgamerzilla_Gamerzilla */

#ifndef _Included_com_identicalsoftware_javalibgamerzilla_Gamerzilla
#define _Included_com_identicalsoftware_javalibgamerzilla_Gamerzilla
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_identicalsoftware_javalibgamerzilla_Gamerzilla
 * Method:    Start
 * Signature: (ZLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_identicalsoftware_javalibgamerzilla_Gamerzilla_Start
  (JNIEnv *, jobject, jboolean, jstring);

/*
 * Class:     com_identicalsoftware_javalibgamerzilla_Gamerzilla
 * Method:    SetGameFromFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_identicalsoftware_javalibgamerzilla_Gamerzilla_SetGameFromFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_identicalsoftware_javalibgamerzilla_Gamerzilla
 * Method:    SetTrophy
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_identicalsoftware_javalibgamerzilla_Gamerzilla_SetTrophy
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_identicalsoftware_javalibgamerzilla_Gamerzilla
 * Method:    Quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_identicalsoftware_javalibgamerzilla_Gamerzilla_Quit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
